<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Exercices</title>
    <link rel="stylesheet" href="css/style.css">
    <script src="js/script.js"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
</head>
<body>
    <section id="container">
        <div class="cards">
            <div class="card" id="card1" onClick="request(1)">
                <h2>Sequential</h2>
                <p>We've an array of 18 arrays, that we need to know if I delete a number the array will have sense in the asc. sequential way, and return true if possible, if not, returns false. Arrays with only one number repeated many times, have to return true.</p>
            </div>
            <div class="card" id="card2"  onClick="request(2)">
                <h2>Prime numbers</h2>
                <p>Here we've to give a prime number, and we'll recieve the lower the lower prime number.</p>
            </div>
            <div class="card" id="card3"  onClick="request(3)">
                <h2>Century</h2>
                <p>Send a number and get the century.</p>
            </div>
            <div class="card" id="card4"  onClick="request(4)">
                <h2>Repeated numbers</h2>
                <p>Getting by a random array, what's the most repeated number and for how many times it was repeated.</p>
            </div>
        </div>
    </section>
</body>
</html>